set_property SRC_FILE_INFO {cfile:C:/Users/fumi/Zybo/practice_adder/practice_adder.srcs/constrs_1/imports/PYNQ-Z1/PYNQ_constraints.xdc rfile:../../../practice_adder.srcs/constrs_1/imports/PYNQ-Z1/PYNQ_constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H16   IOSTANDARD LVCMOS33 } [get_ports {CLK}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L19   IOSTANDARD LVCMOS33 } [get_ports {RST}]
